#!/bin/bash

docker run --rm -it \
           -v "$PWD:/home/dev/work" \
           -v "$HOME/.claude:/home/dev/.claude" \
           -v "$HOME/.claude.json:/home/dev/.claude.json" \
           -w /home/dev/work \
           "cc-container" \
           claude --dangerously-skip-permissions



